from dotenv import load_dotenv
load_dotenv()
import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.graph import travel_graph, classify_intent
from pydantic import BaseModel
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
app = FastAPI(title="AI travel assistant")
from fastapi.middleware.cors import CORSMiddleware

from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="AI travel assistant")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://tripsaarthi-28vm294l2-krishna-0305.vercel.app"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# MODELS
class ChatRequest(BaseModel):
    message: str
    session_id: str = "default-session"


class ChatResponse(BaseModel):
    response: str
    tool_used: str = "none"


@app.get("/")
def query_check():
    return {"status": "running", "app": "AI travel research Assistant"}


# Original non-streaming endpoint — kept for backward compatibility
# and for easy testing via /docs.
@app.post("/ask", response_model=ChatResponse)
def ask(request: ChatRequest):
    print(f"\nRequest: {request.message}")

    config = {"configurable": {"thread_id": request.session_id}}

    result = travel_graph.invoke(
        {
            "messages": [("user", request.message)],
            "question": request.message,
            "research_result": "",
            "weather_result": "",
            "final_answer": "",
            "tool_used": ""
        },
        config=config,
    )

    print(f"Done! Tool used: {result['tool_used']}")

    return ChatResponse(
        response=result["final_answer"],
        tool_used=result["tool_used"]
    )


# NEW: streaming endpoint. Returns tokens as they're generated instead of
# waiting for the whole answer. tool_used is computed up front (using the
# same classify_intent logic the graph uses internally) and sent back as a
# response header, since the streamed body only carries the answer text.
@app.post("/ask/stream")
def ask_stream(request: ChatRequest):
    print(f"\n[Stream] Request: {request.message}")

    config = {"configurable": {"thread_id": request.session_id}}
    tool_used = classify_intent(request.message)

    def token_generator():
        for msg_chunk, metadata in travel_graph.stream(
            {
                "messages": [("user", request.message)],
                "question": request.message,
                "research_result": "",
                "weather_result": "",
                "final_answer": "",
                "tool_used": "",
            },
            config=config,
            stream_mode="messages",
        ):
            # Only forward tokens generated by the Synthesizer node —
            # the Weather Agent also calls the LLM (to extract a city
            # name) and we don't want to leak that to the user.
            if metadata.get("langgraph_node") == "synthesizer" and msg_chunk.content:
                yield msg_chunk.content

    return StreamingResponse(
        token_generator(),
        media_type="text/plain",
        headers={"X-Tool-Used": tool_used},
    )